# Generated by Django 3.0.3 on 2021-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='artist_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
