# Generated by Django 3.0.3 on 2021-07-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0001_initial'),
        ('movies', '0002_auto_20210708_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='artist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.Artists'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.Genres'),
        ),
    ]
